#!/usr/bin/env bash
set -euo pipefail

if [[ ! -f "${KUBECONFIG}" ]]; then
  echo "KUBECONFIG ${KUBECONFIG} does not exist" >&2
  exit 1
fi

kubectl config set-cluster local --server=https://k3s:6443 >/dev/null 2>&1 || true
