# Dataset manifest for kubeply/kubernetes-core
# Add tasks using: harbor add <org>/<name>
# Publish using: harbor publish

[dataset]
name = "kubeply/kubernetes-core"
description = "Kubernetes-first infrastructure benchmark scenarios for AI agents."
keywords = ["kubernetes", "infrastructure", "benchmark", "agents"]
[[dataset.authors]]
name = "Kubeply"
email = "thomas@kubeply.com"


[[tasks]]
name = "kubeply/debug-service-endpoints"
digest = "sha256:5e768bb5a1e91ae4a1b9da31cb82e89d34db54ff6508ba970c26834a3541a51e"


[[files]]
path = "metric.py"
digest = "sha256:52299ec1e5986fcc50c3c13eaeef2e66038b9184b0a9cb69c34d886eb7fcf8a7"
