# Dataset manifest for kubeply/kubernetes-core
# Add tasks using: harbor add <org>/<name>
# Publish using: harbor publish

[dataset]
name = "kubeply/kubernetes-core"
description = "Kubernetes-first infrastructure benchmark scenarios for AI agents."
keywords = ["kubernetes", "infrastructure", "benchmark", "agents"]
[[dataset.authors]]
name = "Kubeply"
email = "thomas@kubeply.com"


[[tasks]]
name = "kubeply/debug-service-endpoints"
digest = "sha256:4454da50bd9ebfb8feb92bc6a76dc9ecd1ee909ef54d5b036ddbe78c520899be"

[[tasks]]
name = "kubeply/repair-readiness-probe-path"
digest = "sha256:5e2b584afe34d91997c5c79048d2c29a79b1d76f269e31768d00bfaf0151df6b"

[[tasks]]
name = "kubeply/fix-config-key-reference"
digest = "sha256:750f4a0ebf167fbf3da93ab3762f378253c31b36cbbb97a584805d2fd4e4a836"

[[tasks]]
name = "kubeply/add-rbac-list-verb"
digest = "sha256:07b2565c5a52b5d76ff93b05f56efa02ff6aabbb90cb136fc415105de19b97f6"

[[tasks]]
name = "kubeply/fix-node-selector-mismatch"
digest = "sha256:72feffcbad96c9f0a2855d0e6dd35281f1455941b5ccdc582af7cc8b9a2bbb86"

[[tasks]]
name = "kubeply/rightsize-cpu-request"
digest = "sha256:237a22bbd6af5a96505184fb6e05ed4be140c6809df2e43e9ae82fd380dd9f7d"


[[files]]
path = "metric.py"
digest = "sha256:52299ec1e5986fcc50c3c13eaeef2e66038b9184b0a9cb69c34d886eb7fcf8a7"
